version: '3.9'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports: ["3306:3306"]
    volumes:
      - dbdata:/var/lib/mysql

  server:
    build: ./server
    command: sh -c "until nc -z db 3306; do echo '⏳ Waiting for db...'; sleep 3; done; npx prisma migrate deploy && node src/index.js"
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      JWT_SECRET: ${JWT_SECRET:-super-secret}
      PORT: 4000
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      - db
    ports:
      - "4000:4000"

  web:
    build: ./web
    environment:
      VITE_API_URL: http://localhost:4000/api
    ports: ["5173:5173"]
    command: npm run dev -- --host
    depends_on: [server]

volumes:
  dbdata:
